// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AdapterCatalogItemResponse
 *
 * Response model for one adapter catalog item.
 */
export type AdapterCatalogItemResponse = {
    /**
     * Adapter Id
     */
    adapter_id: string;
    /**
     * Adapter Name
     */
    adapter_name: string;
    /**
     * Version
     */
    version?: string | null;
    /**
     * Endorsement Count
     */
    endorsement_count?: number;
};

/**
 * AdapterCatalogListResponse
 *
 * Response model for the public adapter catalog.
 */
export type AdapterCatalogListResponse = {
    /**
     * Items
     */
    items: Array<AdapterCatalogItemResponse>;
};

/**
 * AdapterDataSourceResponse
 *
 * Metadata-light dataset summary embedded in adapter Croissant metadata.
 */
export type AdapterDataSourceResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Version
     */
    version?: string | null;
    /**
     * License
     */
    license?: string | null;
    /**
     * Url
     */
    url?: string | null;
    /**
     * Column Count
     */
    column_count?: number | null;
};

/**
 * AdapterDetailResponse
 *
 * Response model for one adapter.
 */
export type AdapterDetailResponse = {
    /**
     * Adapter Id
     */
    adapter_id: string;
    /**
     * Adapter Name
     */
    adapter_name: string;
    /**
     * Version
     */
    version?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Repository Location
     */
    repository_location?: string | null;
    /**
     * License Value
     */
    license_value?: string | null;
    /**
     * Doi
     */
    doi?: string | null;
    /**
     * Cff Url
     */
    cff_url?: string | null;
    /**
     * Keywords
     */
    keywords?: Array<string>;
    /**
     * Maintainers
     */
    maintainers?: Array<AdapterMaintainerResponse>;
    /**
     * Data Sources
     */
    data_sources?: Array<AdapterDataSourceResponse>;
    /**
     * Endorsement Count
     */
    endorsement_count?: number;
    /**
     * Endorsed By Current User
     */
    endorsed_by_current_user?: boolean;
};

/**
 * AdapterEmbeddedDatasetGenerateRequest
 *
 * Generated dataset input embedded in an adapter metadata request.
 */
export type AdapterEmbeddedDatasetGenerateRequest = {
    /**
     * Validate
     */
    validate?: boolean;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Url
     */
    url?: string | null;
    /**
     * License
     */
    license?: string | null;
    /**
     * Citation
     */
    citation?: string | null;
    /**
     * Dataset Version
     */
    dataset_version?: string | null;
    /**
     * Date Published
     */
    date_published?: string | null;
    /**
     * Creators
     */
    creators?: Array<string>;
    /**
     * Extra Args
     */
    extra_args?: Array<string>;
    /**
     * Input
     *
     * Server-side file or directory path used to generate this embedded dataset.
     */
    input: string;
};

/**
 * AdapterEndorsementResponse
 *
 * Current endorsement state for one adapter.
 */
export type AdapterEndorsementResponse = {
    /**
     * Adapter Id
     */
    adapter_id: string;
    /**
     * Endorsement Count
     */
    endorsement_count: number;
    /**
     * Endorsed By Current User
     */
    endorsed_by_current_user?: boolean;
};

/**
 * AdapterLatestItemResponse
 *
 * Response model for one latest-adapters card.
 */
export type AdapterLatestItemResponse = {
    /**
     * Adapter Id
     */
    adapter_id: string;
    /**
     * Adapter Name
     */
    adapter_name: string;
    /**
     * Version
     */
    version?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Repository Location
     */
    repository_location?: string | null;
    /**
     * Keywords
     */
    keywords?: Array<string>;
    /**
     * Maintainers
     */
    maintainers?: Array<AdapterMaintainerResponse>;
    /**
     * Endorsement Count
     */
    endorsement_count?: number;
    /**
     * Endorsed By Current User
     */
    endorsed_by_current_user?: boolean;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * AdapterLatestListResponse
 *
 * Response model for newest adapter cards.
 */
export type AdapterLatestListResponse = {
    /**
     * Items
     */
    items: Array<AdapterLatestItemResponse>;
};

/**
 * AdapterMaintainerResponse
 *
 * Repository maintainer identity for adapter catalog display.
 */
export type AdapterMaintainerResponse = {
    /**
     * Username
     */
    username: string;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    /**
     * Profile Url
     */
    profile_url?: string | null;
};

/**
 * AdapterMetadataGenerateRequest
 *
 * Request body for generating adapter metadata without persisting it.
 */
export type AdapterMetadataGenerateRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Version
     */
    version: string;
    /**
     * License
     */
    license: string;
    /**
     * Code Repository
     */
    code_repository: string;
    /**
     * Dataset Paths
     */
    dataset_paths?: Array<string>;
    /**
     * Generated Datasets
     */
    generated_datasets?: Array<AdapterEmbeddedDatasetGenerateRequest>;
    /**
     * Validate
     */
    validate?: boolean;
    /**
     * Creators
     */
    creators: Array<string>;
    /**
     * Keywords
     */
    keywords: Array<string>;
    /**
     * Adapter Id
     */
    adapter_id?: string | null;
    /**
     * Programming Language
     */
    programming_language?: string;
    /**
     * Target Product
     */
    target_product?: string;
    /**
     * Generator
     */
    generator?: 'native';
    /**
     * Dataset Generator
     */
    dataset_generator?: 'auto' | 'croissant-baker' | 'native';
};

/**
 * AdapterMetadataGenerateResponse
 *
 * Response returned after generating adapter metadata.
 */
export type AdapterMetadataGenerateResponse = {
    /**
     * Metadata
     */
    metadata: {
        [key: string]: unknown;
    };
    /**
     * Generator
     */
    generator: 'native';
    /**
     * Dataset Generator
     */
    dataset_generator: 'auto' | 'croissant-baker' | 'native';
    /**
     * Stdout
     */
    stdout?: string;
    /**
     * Stderr
     */
    stderr?: string;
    /**
     * Warnings
     */
    warnings?: Array<string>;
    validation?: MetadataValidationResponse | null;
};

/**
 * AdapterMetadataResponse
 *
 * Response model for one adapter's full Croissant metadata.
 */
export type AdapterMetadataResponse = {
    /**
     * Adapter Id
     */
    adapter_id: string;
    /**
     * Registry Entry Id
     */
    registry_entry_id: string;
    /**
     * Metadata
     */
    metadata: {
        [key: string]: unknown;
    };
};

/**
 * AuthMeResponse
 *
 * Signed-in GitHub identity shown in the frontend header.
 */
export type AuthMeResponse = {
    /**
     * Github Login
     */
    github_login: string;
};

/**
 * DatasetMetadataGenerateRequest
 *
 * Request body for generating dataset metadata from server-side files.
 */
export type DatasetMetadataGenerateRequest = {
    /**
     * Validate
     */
    validate?: boolean;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Url
     */
    url?: string | null;
    /**
     * License
     */
    license?: string | null;
    /**
     * Citation
     */
    citation?: string | null;
    /**
     * Dataset Version
     */
    dataset_version?: string | null;
    /**
     * Date Published
     */
    date_published?: string | null;
    /**
     * Creators
     */
    creators?: Array<string>;
    /**
     * Extra Args
     */
    extra_args?: Array<string>;
    /**
     * Input Path
     *
     * Server-side file or directory path visible to the backend process.
     */
    input_path: string;
    /**
     * Generator
     *
     * Dataset metadata generator backend.
     */
    generator?: 'auto' | 'croissant-baker' | 'native';
};

/**
 * DatasetMetadataGenerateResponse
 *
 * Response returned after generating dataset metadata.
 */
export type DatasetMetadataGenerateResponse = {
    /**
     * Metadata
     */
    metadata: {
        [key: string]: unknown;
    };
    /**
     * Generator
     */
    generator: 'auto' | 'croissant-baker' | 'native';
    /**
     * Stdout
     */
    stdout?: string;
    /**
     * Stderr
     */
    stderr?: string;
    /**
     * Warnings
     */
    warnings?: Array<string>;
    validation?: MetadataValidationResponse | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 *
 * Health-check response returned by the API.
 */
export type HealthResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Service
     */
    service: string;
};

/**
 * MetadataValidationCheckResponse
 *
 * Response model for one validation layer result.
 */
export type MetadataValidationCheckResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Is Valid
     */
    is_valid: boolean;
    /**
     * Errors
     */
    errors: Array<string>;
};

/**
 * MetadataValidationRequest
 *
 * Request body for validating metadata without persisting it.
 */
export type MetadataValidationRequest = {
    /**
     * Metadata
     *
     * Inline Croissant adapter or dataset metadata document.
     */
    metadata: {
        [key: string]: unknown;
    };
    /**
     * Kind
     *
     * Metadata type to validate. Use auto to infer from the root @type.
     */
    kind?: 'auto' | 'adapter' | 'dataset';
};

/**
 * MetadataValidationResponse
 *
 * Response model for one metadata validation run.
 */
export type MetadataValidationResponse = {
    /**
     * Kind
     */
    kind: 'adapter' | 'dataset';
    /**
     * Is Valid
     */
    is_valid: boolean;
    /**
     * Profile Version
     */
    profile_version: string;
    /**
     * Errors
     */
    errors: Array<string>;
    /**
     * Checks
     */
    checks: Array<MetadataValidationCheckResponse>;
};

/**
 * RegistrationCreateRequest
 *
 * Request body for creating an adapter registration.
 */
export type RegistrationCreateRequest = {
    /**
     * Adapter Name
     *
     * Human-readable adapter name supplied by the maintainer.
     */
    adapter_name: string;
    /**
     * Repository Location
     *
     * Local repository path or supported remote repository URL containing a root-level croissant.jsonld file.
     */
    repository_location: string;
    /**
     * License Value
     *
     * Optional submitted adapter license text.
     */
    license_value?: string | null;
    /**
     * Doi
     *
     * Optional submitted DOI text.
     */
    doi?: string | null;
    /**
     * Cff Url
     *
     * Optional submitted Citation File Format URL.
     */
    cff_url?: string | null;
};

/**
 * RegistrationCreateResponse
 *
 * Response returned after creating an adapter registration.
 */
export type RegistrationCreateResponse = {
    /**
     * Registration Id
     */
    registration_id: string;
    /**
     * Adapter Name
     */
    adapter_name: string;
    /**
     * Adapter Id
     */
    adapter_id: string;
    /**
     * Repository Location
     */
    repository_location: string;
    /**
     * Repository Kind
     */
    repository_kind: 'local' | 'remote' | string;
    status: RegistrationStatus;
    /**
     * Created At
     */
    created_at: string;
    /**
     * License Value
     */
    license_value?: string | null;
    /**
     * Doi
     */
    doi?: string | null;
    /**
     * Cff Url
     */
    cff_url?: string | null;
    /**
     * Submitted By Github Login
     */
    submitted_by_github_login?: string | null;
};

/**
 * RegistrationCroissantFilePresentCheckResponse
 *
 * Response model for a remote croissant.jsonld presence check.
 */
export type RegistrationCroissantFilePresentCheckResponse = {
    /**
     * Has Croissant File
     */
    has_croissant_file: boolean;
};

/**
 * RegistrationDetailResponse
 *
 * Detailed response for one stored registration.
 */
export type RegistrationDetailResponse = {
    /**
     * Registration Id
     */
    registration_id: string;
    /**
     * Adapter Name
     */
    adapter_name: string;
    /**
     * Adapter Id
     */
    adapter_id: string;
    /**
     * Repository Location
     */
    repository_location: string;
    /**
     * Repository Kind
     */
    repository_kind: 'local' | 'remote' | string;
    status: RegistrationStatus;
    /**
     * Created At
     */
    created_at: string;
    /**
     * License Value
     */
    license_value?: string | null;
    /**
     * Doi
     */
    doi?: string | null;
    /**
     * Cff Url
     */
    cff_url?: string | null;
    /**
     * Submitted By Github Login
     */
    submitted_by_github_login?: string | null;
    /**
     * Metadata Path
     */
    metadata_path?: string | null;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
    /**
     * Profile Version
     */
    profile_version?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Uniqueness Key
     */
    uniqueness_key?: string | null;
    /**
     * Validation Errors
     */
    validation_errors?: Array<string> | null;
};

/**
 * RegistrationEventListResponse
 *
 * Response model for a registration event history list.
 */
export type RegistrationEventListResponse = {
    /**
     * Items
     */
    items: Array<RegistrationEventResponse>;
};

/**
 * RegistrationEventResponse
 *
 * Response model for one registration event.
 */
export type RegistrationEventResponse = {
    /**
     * Event Id
     */
    event_id: string;
    /**
     * Source Id
     */
    source_id: string;
    /**
     * Registry Entry Id
     */
    registry_entry_id?: string | null;
    /**
     * Event Type
     */
    event_type: string;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Profile Version
     */
    profile_version?: string | null;
    /**
     * Error Details
     */
    error_details?: Array<string> | null;
    /**
     * Observed Checksum
     */
    observed_checksum?: string | null;
    /**
     * Mlcroissant Valid
     */
    mlcroissant_valid?: boolean | null;
    /**
     * Schema Valid
     */
    schema_valid?: boolean | null;
    /**
     * Started At
     */
    started_at?: string | null;
    /**
     * Finished At
     */
    finished_at?: string | null;
};

/**
 * RegistrationListItemResponse
 *
 * Summary response model for one registration in a list.
 */
export type RegistrationListItemResponse = {
    /**
     * Registration Id
     */
    registration_id: string;
    /**
     * Adapter Name
     */
    adapter_name: string;
    /**
     * Adapter Id
     */
    adapter_id: string;
    /**
     * Repository Location
     */
    repository_location: string;
    /**
     * Repository Kind
     */
    repository_kind: 'local' | 'remote' | string;
    status: RegistrationStatus;
    /**
     * Created At
     */
    created_at: string;
    /**
     * License Value
     */
    license_value?: string | null;
    /**
     * Doi
     */
    doi?: string | null;
    /**
     * Cff Url
     */
    cff_url?: string | null;
    /**
     * Submitted By Github Login
     */
    submitted_by_github_login?: string | null;
    /**
     * Profile Version
     */
    profile_version?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Uniqueness Key
     */
    uniqueness_key?: string | null;
};

/**
 * RegistrationListResponse
 *
 * Response model for a registration list.
 */
export type RegistrationListResponse = {
    /**
     * Items
     */
    items: Array<RegistrationListItemResponse>;
};

/**
 * RegistrationProcessResponse
 *
 * Response returned after processing one registration.
 */
export type RegistrationProcessResponse = {
    /**
     * Registration Id
     */
    registration_id: string;
    /**
     * Adapter Name
     */
    adapter_name: string;
    /**
     * Adapter Id
     */
    adapter_id: string;
    /**
     * Repository Location
     */
    repository_location: string;
    /**
     * Repository Kind
     */
    repository_kind: 'local' | 'remote' | string;
    status: RegistrationStatus;
    /**
     * Created At
     */
    created_at: string;
    /**
     * License Value
     */
    license_value?: string | null;
    /**
     * Doi
     */
    doi?: string | null;
    /**
     * Cff Url
     */
    cff_url?: string | null;
    /**
     * Submitted By Github Login
     */
    submitted_by_github_login?: string | null;
    /**
     * Metadata Path
     */
    metadata_path?: string | null;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
    /**
     * Profile Version
     */
    profile_version?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Uniqueness Key
     */
    uniqueness_key?: string | null;
    /**
     * Validation Errors
     */
    validation_errors?: Array<string> | null;
};

/**
 * RegistrationRevalidateResponse
 *
 * Response returned after revalidating one registration.
 */
export type RegistrationRevalidateResponse = {
    /**
     * Registration Id
     */
    registration_id: string;
    /**
     * Adapter Name
     */
    adapter_name: string;
    /**
     * Adapter Id
     */
    adapter_id: string;
    /**
     * Repository Location
     */
    repository_location: string;
    /**
     * Repository Kind
     */
    repository_kind: 'local' | 'remote' | string;
    status: RegistrationStatus;
    /**
     * Created At
     */
    created_at: string;
    /**
     * License Value
     */
    license_value?: string | null;
    /**
     * Doi
     */
    doi?: string | null;
    /**
     * Cff Url
     */
    cff_url?: string | null;
    /**
     * Submitted By Github Login
     */
    submitted_by_github_login?: string | null;
    /**
     * Metadata Path
     */
    metadata_path?: string | null;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
    /**
     * Profile Version
     */
    profile_version?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Uniqueness Key
     */
    uniqueness_key?: string | null;
    /**
     * Validation Errors
     */
    validation_errors?: Array<string> | null;
};

/**
 * RegistrationStatus
 *
 * Tracked states for a stored registration request.
 */
export type RegistrationStatus = 'SUBMITTED' | 'VALID' | 'INVALID';

/**
 * RegistryEntryListResponse
 *
 * Response model for canonical registry entries.
 */
export type RegistryEntryListResponse = {
    /**
     * Items
     */
    items: Array<RegistryEntryResponse>;
};

/**
 * RegistryEntryResponse
 *
 * Response model for one canonical registry entry.
 */
export type RegistryEntryResponse = {
    /**
     * Entry Id
     */
    entry_id: string;
    /**
     * Source Id
     */
    source_id: string;
    /**
     * Adapter Name
     */
    adapter_name: string;
    /**
     * Adapter Version
     */
    adapter_version?: string | null;
    /**
     * Profile Version
     */
    profile_version?: string | null;
    /**
     * Uniqueness Key
     */
    uniqueness_key: string;
    /**
     * Metadata Checksum
     */
    metadata_checksum?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Is Active
     */
    is_active: boolean;
};

/**
 * RegistryRefreshLatestResponse
 *
 * Response model for the latest persisted registry refresh.
 */
export type RegistryRefreshLatestResponse = {
    /**
     * Refresh Id
     */
    refresh_id: string;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Finished At
     */
    finished_at: string;
    /**
     * Active Sources
     */
    active_sources: number;
    /**
     * Processed
     */
    processed: number;
    /**
     * Valid Created
     */
    valid_created: number;
    /**
     * Unchanged
     */
    unchanged: number;
    /**
     * Invalid
     */
    invalid: number;
    /**
     * Duplicate
     */
    duplicate: number;
    /**
     * Rejected Same Version Changed
     */
    rejected_same_version_changed: number;
    /**
     * Fetch Failed
     */
    fetch_failed: number;
};

/**
 * RegistryRefreshResponse
 *
 * Response returned after refreshing active registration sources.
 */
export type RegistryRefreshResponse = {
    /**
     * Active Sources
     */
    active_sources: number;
    /**
     * Processed
     */
    processed: number;
    /**
     * Valid Created
     */
    valid_created: number;
    /**
     * Unchanged
     */
    unchanged: number;
    /**
     * Invalid
     */
    invalid: number;
    /**
     * Duplicate
     */
    duplicate: number;
    /**
     * Rejected Same Version Changed
     */
    rejected_same_version_changed: number;
    /**
     * Fetch Failed
     */
    fetch_failed: number;
};

/**
 * RegistryRegistrationListResponse
 *
 * Response model for registry registration overview rows.
 */
export type RegistryRegistrationListResponse = {
    /**
     * Items
     */
    items: Array<RegistryRegistrationResponse>;
};

/**
 * RegistryRegistrationResponse
 *
 * Response model for one registry registration overview row.
 */
export type RegistryRegistrationResponse = {
    /**
     * Registration Id
     */
    registration_id: string;
    /**
     * Adapter Name
     */
    adapter_name: string;
    /**
     * Adapter Id
     */
    adapter_id: string;
    /**
     * Repository Kind
     */
    repository_kind: string;
    /**
     * Repository Location
     */
    repository_location: string;
    status: RegistrationStatus;
    /**
     * Latest Event Type
     */
    latest_event_type: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Profile Version
     */
    profile_version?: string | null;
    /**
     * Uniqueness Key
     */
    uniqueness_key?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type GetMeApiV1AuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type GetMeApiV1AuthMeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMeApiV1AuthMeGetError = GetMeApiV1AuthMeGetErrors[keyof GetMeApiV1AuthMeGetErrors];

export type GetMeApiV1AuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: AuthMeResponse;
};

export type GetMeApiV1AuthMeGetResponse = GetMeApiV1AuthMeGetResponses[keyof GetMeApiV1AuthMeGetResponses];

export type LogoutApiV1AuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutApiV1AuthLogoutPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogoutApiV1AuthLogoutPostError = LogoutApiV1AuthLogoutPostErrors[keyof LogoutApiV1AuthLogoutPostErrors];

export type LogoutApiV1AuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutApiV1AuthLogoutPostResponse = LogoutApiV1AuthLogoutPostResponses[keyof LogoutApiV1AuthLogoutPostResponses];

export type HealthCheckApiV1HealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type HealthCheckApiV1HealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthCheckApiV1HealthGetResponse = HealthCheckApiV1HealthGetResponses[keyof HealthCheckApiV1HealthGetResponses];

export type ListAdaptersApiV1AdaptersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/adapters';
};

export type ListAdaptersApiV1AdaptersGetResponses = {
    /**
     * Successful Response
     */
    200: AdapterCatalogListResponse;
};

export type ListAdaptersApiV1AdaptersGetResponse = ListAdaptersApiV1AdaptersGetResponses[keyof ListAdaptersApiV1AdaptersGetResponses];

export type ListLatestAdaptersApiV1AdaptersLatestGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/adapters/latest';
};

export type ListLatestAdaptersApiV1AdaptersLatestGetResponses = {
    /**
     * Successful Response
     */
    200: AdapterLatestListResponse;
};

export type ListLatestAdaptersApiV1AdaptersLatestGetResponse = ListLatestAdaptersApiV1AdaptersLatestGetResponses[keyof ListLatestAdaptersApiV1AdaptersLatestGetResponses];

export type SearchAdaptersApiV1AdaptersSearchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Query
         */
        query: string;
    };
    url: '/api/v1/adapters/search';
};

export type SearchAdaptersApiV1AdaptersSearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchAdaptersApiV1AdaptersSearchGetError = SearchAdaptersApiV1AdaptersSearchGetErrors[keyof SearchAdaptersApiV1AdaptersSearchGetErrors];

export type SearchAdaptersApiV1AdaptersSearchGetResponses = {
    /**
     * Successful Response
     */
    200: AdapterLatestListResponse;
};

export type SearchAdaptersApiV1AdaptersSearchGetResponse = SearchAdaptersApiV1AdaptersSearchGetResponses[keyof SearchAdaptersApiV1AdaptersSearchGetResponses];

export type GetAdapterApiV1AdaptersAdapterIdGetData = {
    body?: never;
    path: {
        /**
         * Adapter Id
         */
        adapter_id: string;
    };
    query?: never;
    url: '/api/v1/adapters/{adapter_id}';
};

export type GetAdapterApiV1AdaptersAdapterIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAdapterApiV1AdaptersAdapterIdGetError = GetAdapterApiV1AdaptersAdapterIdGetErrors[keyof GetAdapterApiV1AdaptersAdapterIdGetErrors];

export type GetAdapterApiV1AdaptersAdapterIdGetResponses = {
    /**
     * Successful Response
     */
    200: AdapterDetailResponse;
};

export type GetAdapterApiV1AdaptersAdapterIdGetResponse = GetAdapterApiV1AdaptersAdapterIdGetResponses[keyof GetAdapterApiV1AdaptersAdapterIdGetResponses];

export type EndorseAdapterApiV1AdaptersAdapterIdEndorsePostData = {
    body?: never;
    path: {
        /**
         * Adapter Id
         */
        adapter_id: string;
    };
    query?: never;
    url: '/api/v1/adapters/{adapter_id}/endorse';
};

export type EndorseAdapterApiV1AdaptersAdapterIdEndorsePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EndorseAdapterApiV1AdaptersAdapterIdEndorsePostError = EndorseAdapterApiV1AdaptersAdapterIdEndorsePostErrors[keyof EndorseAdapterApiV1AdaptersAdapterIdEndorsePostErrors];

export type EndorseAdapterApiV1AdaptersAdapterIdEndorsePostResponses = {
    /**
     * Successful Response
     */
    200: AdapterEndorsementResponse;
};

export type EndorseAdapterApiV1AdaptersAdapterIdEndorsePostResponse = EndorseAdapterApiV1AdaptersAdapterIdEndorsePostResponses[keyof EndorseAdapterApiV1AdaptersAdapterIdEndorsePostResponses];

export type GetAdapterMetadataApiV1AdaptersAdapterIdMetadataGetData = {
    body?: never;
    path: {
        /**
         * Adapter Id
         */
        adapter_id: string;
    };
    query?: never;
    url: '/api/v1/adapters/{adapter_id}/metadata';
};

export type GetAdapterMetadataApiV1AdaptersAdapterIdMetadataGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAdapterMetadataApiV1AdaptersAdapterIdMetadataGetError = GetAdapterMetadataApiV1AdaptersAdapterIdMetadataGetErrors[keyof GetAdapterMetadataApiV1AdaptersAdapterIdMetadataGetErrors];

export type GetAdapterMetadataApiV1AdaptersAdapterIdMetadataGetResponses = {
    /**
     * Successful Response
     */
    200: AdapterMetadataResponse;
};

export type GetAdapterMetadataApiV1AdaptersAdapterIdMetadataGetResponse = GetAdapterMetadataApiV1AdaptersAdapterIdMetadataGetResponses[keyof GetAdapterMetadataApiV1AdaptersAdapterIdMetadataGetResponses];

export type ValidateMetadataApiV1MetadataValidatePostData = {
    body: MetadataValidationRequest;
    path?: never;
    query?: never;
    url: '/api/v1/metadata/validate';
};

export type ValidateMetadataApiV1MetadataValidatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ValidateMetadataApiV1MetadataValidatePostError = ValidateMetadataApiV1MetadataValidatePostErrors[keyof ValidateMetadataApiV1MetadataValidatePostErrors];

export type ValidateMetadataApiV1MetadataValidatePostResponses = {
    /**
     * Successful Response
     */
    200: MetadataValidationResponse;
};

export type ValidateMetadataApiV1MetadataValidatePostResponse = ValidateMetadataApiV1MetadataValidatePostResponses[keyof ValidateMetadataApiV1MetadataValidatePostResponses];

export type GenerateDatasetMetadataApiV1MetadataDatasetsGeneratePostData = {
    body: DatasetMetadataGenerateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/metadata/datasets/generate';
};

export type GenerateDatasetMetadataApiV1MetadataDatasetsGeneratePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateDatasetMetadataApiV1MetadataDatasetsGeneratePostError = GenerateDatasetMetadataApiV1MetadataDatasetsGeneratePostErrors[keyof GenerateDatasetMetadataApiV1MetadataDatasetsGeneratePostErrors];

export type GenerateDatasetMetadataApiV1MetadataDatasetsGeneratePostResponses = {
    /**
     * Successful Response
     */
    200: DatasetMetadataGenerateResponse;
};

export type GenerateDatasetMetadataApiV1MetadataDatasetsGeneratePostResponse = GenerateDatasetMetadataApiV1MetadataDatasetsGeneratePostResponses[keyof GenerateDatasetMetadataApiV1MetadataDatasetsGeneratePostResponses];

export type GenerateAdapterMetadataApiV1MetadataAdaptersGeneratePostData = {
    body: AdapterMetadataGenerateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/metadata/adapters/generate';
};

export type GenerateAdapterMetadataApiV1MetadataAdaptersGeneratePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateAdapterMetadataApiV1MetadataAdaptersGeneratePostError = GenerateAdapterMetadataApiV1MetadataAdaptersGeneratePostErrors[keyof GenerateAdapterMetadataApiV1MetadataAdaptersGeneratePostErrors];

export type GenerateAdapterMetadataApiV1MetadataAdaptersGeneratePostResponses = {
    /**
     * Successful Response
     */
    200: AdapterMetadataGenerateResponse;
};

export type GenerateAdapterMetadataApiV1MetadataAdaptersGeneratePostResponse = GenerateAdapterMetadataApiV1MetadataAdaptersGeneratePostResponses[keyof GenerateAdapterMetadataApiV1MetadataAdaptersGeneratePostResponses];

export type ListRegistrationsApiV1RegistrationsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/registrations';
};

export type ListRegistrationsApiV1RegistrationsGetResponses = {
    /**
     * Successful Response
     */
    200: RegistrationListResponse;
};

export type ListRegistrationsApiV1RegistrationsGetResponse = ListRegistrationsApiV1RegistrationsGetResponses[keyof ListRegistrationsApiV1RegistrationsGetResponses];

export type CreateRegistrationApiV1RegistrationsPostData = {
    body: RegistrationCreateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/registrations';
};

export type CreateRegistrationApiV1RegistrationsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRegistrationApiV1RegistrationsPostError = CreateRegistrationApiV1RegistrationsPostErrors[keyof CreateRegistrationApiV1RegistrationsPostErrors];

export type CreateRegistrationApiV1RegistrationsPostResponses = {
    /**
     * Successful Response
     */
    201: RegistrationCreateResponse;
};

export type CreateRegistrationApiV1RegistrationsPostResponse = CreateRegistrationApiV1RegistrationsPostResponses[keyof CreateRegistrationApiV1RegistrationsPostResponses];

export type CheckRegistrationCroissantFilePresenceApiV1RegistrationsCroissantFilePresentCheckGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Repository Url
         */
        repository_url: string;
    };
    url: '/api/v1/registrations/croissant-file-present-check';
};

export type CheckRegistrationCroissantFilePresenceApiV1RegistrationsCroissantFilePresentCheckGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckRegistrationCroissantFilePresenceApiV1RegistrationsCroissantFilePresentCheckGetError = CheckRegistrationCroissantFilePresenceApiV1RegistrationsCroissantFilePresentCheckGetErrors[keyof CheckRegistrationCroissantFilePresenceApiV1RegistrationsCroissantFilePresentCheckGetErrors];

export type CheckRegistrationCroissantFilePresenceApiV1RegistrationsCroissantFilePresentCheckGetResponses = {
    /**
     * Successful Response
     */
    200: RegistrationCroissantFilePresentCheckResponse;
};

export type CheckRegistrationCroissantFilePresenceApiV1RegistrationsCroissantFilePresentCheckGetResponse = CheckRegistrationCroissantFilePresenceApiV1RegistrationsCroissantFilePresentCheckGetResponses[keyof CheckRegistrationCroissantFilePresenceApiV1RegistrationsCroissantFilePresentCheckGetResponses];

export type ListRegistrationEventsApiV1RegistrationsRegistrationIdEventsGetData = {
    body?: never;
    path: {
        /**
         * Registration Id
         */
        registration_id: string;
    };
    query?: never;
    url: '/api/v1/registrations/{registration_id}/events';
};

export type ListRegistrationEventsApiV1RegistrationsRegistrationIdEventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRegistrationEventsApiV1RegistrationsRegistrationIdEventsGetError = ListRegistrationEventsApiV1RegistrationsRegistrationIdEventsGetErrors[keyof ListRegistrationEventsApiV1RegistrationsRegistrationIdEventsGetErrors];

export type ListRegistrationEventsApiV1RegistrationsRegistrationIdEventsGetResponses = {
    /**
     * Successful Response
     */
    200: RegistrationEventListResponse;
};

export type ListRegistrationEventsApiV1RegistrationsRegistrationIdEventsGetResponse = ListRegistrationEventsApiV1RegistrationsRegistrationIdEventsGetResponses[keyof ListRegistrationEventsApiV1RegistrationsRegistrationIdEventsGetResponses];

export type GetRegistrationApiV1RegistrationsRegistrationIdGetData = {
    body?: never;
    path: {
        /**
         * Registration Id
         */
        registration_id: string;
    };
    query?: never;
    url: '/api/v1/registrations/{registration_id}';
};

export type GetRegistrationApiV1RegistrationsRegistrationIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRegistrationApiV1RegistrationsRegistrationIdGetError = GetRegistrationApiV1RegistrationsRegistrationIdGetErrors[keyof GetRegistrationApiV1RegistrationsRegistrationIdGetErrors];

export type GetRegistrationApiV1RegistrationsRegistrationIdGetResponses = {
    /**
     * Successful Response
     */
    200: RegistrationDetailResponse;
};

export type GetRegistrationApiV1RegistrationsRegistrationIdGetResponse = GetRegistrationApiV1RegistrationsRegistrationIdGetResponses[keyof GetRegistrationApiV1RegistrationsRegistrationIdGetResponses];

export type ProcessRegistrationApiV1RegistrationsRegistrationIdProcessPostData = {
    body?: never;
    path: {
        /**
         * Registration Id
         */
        registration_id: string;
    };
    query?: never;
    url: '/api/v1/registrations/{registration_id}/process';
};

export type ProcessRegistrationApiV1RegistrationsRegistrationIdProcessPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProcessRegistrationApiV1RegistrationsRegistrationIdProcessPostError = ProcessRegistrationApiV1RegistrationsRegistrationIdProcessPostErrors[keyof ProcessRegistrationApiV1RegistrationsRegistrationIdProcessPostErrors];

export type ProcessRegistrationApiV1RegistrationsRegistrationIdProcessPostResponses = {
    /**
     * Successful Response
     */
    200: RegistrationProcessResponse;
};

export type ProcessRegistrationApiV1RegistrationsRegistrationIdProcessPostResponse = ProcessRegistrationApiV1RegistrationsRegistrationIdProcessPostResponses[keyof ProcessRegistrationApiV1RegistrationsRegistrationIdProcessPostResponses];

export type RevalidateRegistrationRouteApiV1RegistrationsRegistrationIdRevalidatePostData = {
    body?: never;
    path: {
        /**
         * Registration Id
         */
        registration_id: string;
    };
    query?: never;
    url: '/api/v1/registrations/{registration_id}/revalidate';
};

export type RevalidateRegistrationRouteApiV1RegistrationsRegistrationIdRevalidatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevalidateRegistrationRouteApiV1RegistrationsRegistrationIdRevalidatePostError = RevalidateRegistrationRouteApiV1RegistrationsRegistrationIdRevalidatePostErrors[keyof RevalidateRegistrationRouteApiV1RegistrationsRegistrationIdRevalidatePostErrors];

export type RevalidateRegistrationRouteApiV1RegistrationsRegistrationIdRevalidatePostResponses = {
    /**
     * Successful Response
     */
    200: RegistrationRevalidateResponse;
};

export type RevalidateRegistrationRouteApiV1RegistrationsRegistrationIdRevalidatePostResponse = RevalidateRegistrationRouteApiV1RegistrationsRegistrationIdRevalidatePostResponses[keyof RevalidateRegistrationRouteApiV1RegistrationsRegistrationIdRevalidatePostResponses];

export type ListRegistryRegistrationsApiV1RegistryRegistrationsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Status
         *
         * Filter registry registrations by public registration status.
         */
        status?: RegistrationStatus | null;
        /**
         * Latest Event
         *
         * Filter by latest registration event type, such as VALID_CREATED, INVALID_SCHEMA, or FETCH_FAILED.
         */
        latest_event?: 'SUBMITTED' | 'VALID_CREATED' | 'UNCHANGED' | 'DUPLICATE' | 'REJECTED_SAME_VERSION_CHANGED' | 'INVALID_SCHEMA' | 'INVALID_MLCROISSANT' | 'INVALID_BOTH' | 'FETCH_FAILED' | 'REVALIDATED' | null;
    };
    url: '/api/v1/registry/registrations';
};

export type ListRegistryRegistrationsApiV1RegistryRegistrationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRegistryRegistrationsApiV1RegistryRegistrationsGetError = ListRegistryRegistrationsApiV1RegistryRegistrationsGetErrors[keyof ListRegistryRegistrationsApiV1RegistryRegistrationsGetErrors];

export type ListRegistryRegistrationsApiV1RegistryRegistrationsGetResponses = {
    /**
     * Successful Response
     */
    200: RegistryRegistrationListResponse;
};

export type ListRegistryRegistrationsApiV1RegistryRegistrationsGetResponse = ListRegistryRegistrationsApiV1RegistryRegistrationsGetResponses[keyof ListRegistryRegistrationsApiV1RegistryRegistrationsGetResponses];

export type ListRegistryEntriesApiV1RegistryEntriesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/registry/entries';
};

export type ListRegistryEntriesApiV1RegistryEntriesGetResponses = {
    /**
     * Successful Response
     */
    200: RegistryEntryListResponse;
};

export type ListRegistryEntriesApiV1RegistryEntriesGetResponse = ListRegistryEntriesApiV1RegistryEntriesGetResponses[keyof ListRegistryEntriesApiV1RegistryEntriesGetResponses];

export type GetRegistryEntryApiV1RegistryEntriesEntryIdGetData = {
    body?: never;
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
    };
    query?: never;
    url: '/api/v1/registry/entries/{entry_id}';
};

export type GetRegistryEntryApiV1RegistryEntriesEntryIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRegistryEntryApiV1RegistryEntriesEntryIdGetError = GetRegistryEntryApiV1RegistryEntriesEntryIdGetErrors[keyof GetRegistryEntryApiV1RegistryEntriesEntryIdGetErrors];

export type GetRegistryEntryApiV1RegistryEntriesEntryIdGetResponses = {
    /**
     * Successful Response
     */
    200: RegistryEntryResponse;
};

export type GetRegistryEntryApiV1RegistryEntriesEntryIdGetResponse = GetRegistryEntryApiV1RegistryEntriesEntryIdGetResponses[keyof GetRegistryEntryApiV1RegistryEntriesEntryIdGetResponses];

export type GetLatestRegistryRefreshApiV1RegistryRefreshesLatestGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/registry/refreshes/latest';
};

export type GetLatestRegistryRefreshApiV1RegistryRefreshesLatestGetResponses = {
    /**
     * Successful Response
     */
    200: RegistryRefreshLatestResponse;
};

export type GetLatestRegistryRefreshApiV1RegistryRefreshesLatestGetResponse = GetLatestRegistryRefreshApiV1RegistryRefreshesLatestGetResponses[keyof GetLatestRegistryRefreshApiV1RegistryRefreshesLatestGetResponses];

export type CreateRegistryRefreshApiV1RegistryRefreshesPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/registry/refreshes';
};

export type CreateRegistryRefreshApiV1RegistryRefreshesPostResponses = {
    /**
     * Successful Response
     */
    200: RegistryRefreshResponse;
};

export type CreateRegistryRefreshApiV1RegistryRefreshesPostResponse = CreateRegistryRefreshApiV1RegistryRefreshesPostResponses[keyof CreateRegistryRefreshApiV1RegistryRefreshesPostResponses];
