# Configuration for SonarQube Cloud Automatic Analysis.
# Note: this file is used instead of sonar-project.properties, which is
# ignored when Automatic Analysis is enabled.
# https://docs.sonarsource.com/sonarqube-cloud/analyzing-source-code/automatic-analysis

# Source encoding
sonar.sourceEncoding=UTF-8

# Python version (for python projects only)
sonar.python.version=3.12
