services:
  frontend:
    image: ghcr.io/ssciwr/biocypher-components-registry/frontend:v0.1.0
    env_file: .env
    environment:
      # When integrating, adjust this in .env.
      BACKEND_INTERNAL_URL: ${BACKEND_INTERNAL_URL:-http://backend:8000}
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - biocypher-network

  backend:
    image: ghcr.io/ssciwr/biocypher-components-registry/backend:0.1.0
    env_file: .env
    environment:
      BIOCYPHER_REGISTRY_DB_PATH: /app/data/registry.sqlite3
    volumes:
      - biocypher-sqlite-data:/app/data
    networks:
      - biocypher-network

networks:
  biocypher-network:
    driver: bridge

volumes:
  biocypher-sqlite-data:
    driver: local
