// This file is auto-generated by @hey-api/openapi-ts

type Slot = 'body' | 'headers' | 'path' | 'query';

export type Field =
  | {
      in: Exclude<Slot, 'body'>;
      /**
       * Field name. This is the name we want the user to see and use.
       */
      key: string;
      /**
       * Field mapped name. This is the name we want to use in the request.
       * If omitted, we use the same value as `key`.
       */
      map?: string;
    }
  | {
      in: Extract<Slot, 'body'>;
      /**
       * Key isn't required for bodies.
       */
      key?: string;
      map?: string;
    }
  | {
      /**
       * Field name. This is the name we want the user to see and use.
       */
      key: string;
      /**
       * Field mapped name. This is the name we want to use in the request.
       * If `in` is omitted, `map` aliases `key` to the transport layer.
       */
      map: Slot;
    };

export interface Fields {
  allowExtra?: Partial<Record<Slot, boolean>>;
  args?: ReadonlyArray<Field>;
}

export type FieldsConfig = ReadonlyArray<Field | Fields>;

const extraPrefixesMap: Record<string, Slot> = {
  $body_: 'body',
  $headers_: 'headers',
  $path_: 'path',
  $query_: 'query',
};
const extraPrefixes = Object.entries(extraPrefixesMap);

type KeyMapEntry =
  | {
      in: Slot;
      map?: string;
    }
  | {
      in?: never;
      map: Slot;
    };

type KeyMap = Map<string, KeyMapEntry>;

function buildKeyMap(fields: FieldsConfig, map?: KeyMap): KeyMap {
  map ??= new Map();

  for (const config of fields) {
    if ('in' in config) {
      if (config.key) {
        map.set(config.key, {
          in: config.in,
          map: config.map,
        });
      }
    } else if ('key' in config) {
      map.set(config.key, {
        map: config.map,
      });
    } else if (config.args) {
      buildKeyMap(config.args, map);
    }
  }

  return map;
}

interface Params {
  body?: unknown;
  headers: Record<string, unknown>;
  path: Record<string, unknown>;
  query: Record<string, unknown>;
}

function stripEmptySlots(params: Params): void {
  for (const [slot, value] of Object.entries(params)) {
    if (slot === 'body') continue;
    if (value && typeof value === 'object' && !Array.isArray(value) && !Object.keys(value).length) {
      delete params[slot as Slot];
    }
  }
}

/*
 * AI-Generated.
 */
function createParams(): Params {
  return {
    headers: Object.create(null),
    path: Object.create(null),
    query: Object.create(null),
  };
}

/*
 * AI-Generated.
 */
function writeSlot(params: Params, slot: Slot, key: string, value: unknown): void {
  let record = params[slot] as Record<string, unknown> | undefined;
  if (record === undefined) {
    record = Object.create(null) as Record<string, unknown>;
    params[slot] = record;
  }
  record[key] = value;
}

/*
 * AI-Generated.
 */
function writeMappedField(
  params: Params,
  field: KeyMapEntry,
  key: string,
  value: unknown,
): void {
  if (field.in) {
    writeSlot(params, field.in, field.map || key, value);
    return;
  }
  (params as Partial<Record<Slot, unknown>>)[field.map] = value;
}

/*
 * AI-Generated.
 */
function writeExtraPrefixedParam(params: Params, key: string, value: unknown): boolean {
  const extra = extraPrefixes.find(([prefix]) => key.startsWith(prefix));
  if (!extra) {
    return false;
  }

  const [prefix, slot] = extra;
  writeSlot(params, slot, key.slice(prefix.length), value);
  return true;
}

/*
 * AI-Generated.
 */
function writeAllowedExtraParam(
  params: Params,
  config: FieldsConfig[number],
  key: string,
  value: unknown,
): void {
  if (!('allowExtra' in config) || !config.allowExtra) {
    return;
  }

  for (const [slot, allowed] of Object.entries(config.allowExtra)) {
    if (allowed) {
      writeSlot(params, slot as Slot, key, value);
      return;
    }
  }
}

/*
 * AI-Generated.
 */
function writeObjectParam(
  params: Params,
  map: KeyMap,
  config: FieldsConfig[number],
  key: string,
  value: unknown,
): void {
  const field = map.get(key);
  if (field) {
    writeMappedField(params, field, key, value);
    return;
  }

  if (!writeExtraPrefixedParam(params, key, value)) {
    writeAllowedExtraParam(params, config, key, value);
  }
}

/*
 * AI-Generated.
 */
function writeDirectFieldConfig(
  params: Params,
  map: KeyMap,
  config: Field & { in: Slot },
  arg: unknown,
): void {
  if (!config.key) {
    params.body = arg;
    return;
  }

  writeMappedField(params, map.get(config.key)!, config.key, arg);
}

/*
 * AI-Generated.
 */
function writeConfigArg(
  params: Params,
  map: KeyMap,
  config: FieldsConfig[number],
  arg: unknown,
): void {
  if ('in' in config) {
    writeDirectFieldConfig(params, map, config, arg);
    return;
  }

  for (const [key, value] of Object.entries(arg ?? {})) {
    writeObjectParam(params, map, config, key, value);
  }
}

export function buildClientParams(args: ReadonlyArray<unknown>, fields: FieldsConfig): Params {
  const params = createParams();
  const map = buildKeyMap(fields);
  let config: FieldsConfig[number] | undefined;

  for (const [index, arg] of args.entries()) {
    config = fields[index] || config;
    if (config) {
      writeConfigArg(params, map, config, arg);
    }
  }

  stripEmptySlots(params);

  return params;
}
