// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, ServerSentEventsResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateSessionAgentApiV1SessionsPostData, CreateSessionAgentApiV1SessionsPostErrors, CreateSessionAgentApiV1SessionsPostResponses, DeleteFileAgentApiV1SessionsSessionIdFileDeleteData, DeleteFileAgentApiV1SessionsSessionIdFileDeleteErrors, DeleteFileAgentApiV1SessionsSessionIdFileDeleteResponses, DeleteSessionAgentApiV1SessionsSessionIdDeleteData, DeleteSessionAgentApiV1SessionsSessionIdDeleteErrors, DeleteSessionAgentApiV1SessionsSessionIdDeleteResponses, EventsAgentApiV1SessionsSessionIdEventsGetData, EventsAgentApiV1SessionsSessionIdEventsGetErrors, EventsAgentApiV1SessionsSessionIdEventsGetResponse, EventsAgentApiV1SessionsSessionIdEventsGetResponses, GetSessionAgentApiV1SessionsSessionIdGetData, GetSessionAgentApiV1SessionsSessionIdGetErrors, GetSessionAgentApiV1SessionsSessionIdGetResponses, InterruptAgentApiV1SessionsSessionIdInterruptPostData, InterruptAgentApiV1SessionsSessionIdInterruptPostErrors, InterruptAgentApiV1SessionsSessionIdInterruptPostResponses, ListFilesAgentApiV1SessionsSessionIdFilesGetData, ListFilesAgentApiV1SessionsSessionIdFilesGetErrors, ListFilesAgentApiV1SessionsSessionIdFilesGetResponses, PostMessageAgentApiV1SessionsSessionIdMessagesPostData, PostMessageAgentApiV1SessionsSessionIdMessagesPostErrors, PostMessageAgentApiV1SessionsSessionIdMessagesPostResponses, ReadFileAgentApiV1SessionsSessionIdFileGetData, ReadFileAgentApiV1SessionsSessionIdFileGetErrors, ReadFileAgentApiV1SessionsSessionIdFileGetResponses, SetKeyAgentApiV1SessionsSessionIdKeyPostData, SetKeyAgentApiV1SessionsSessionIdKeyPostErrors, SetKeyAgentApiV1SessionsSessionIdKeyPostResponses, WriteFileAgentApiV1SessionsSessionIdFilePutData, WriteFileAgentApiV1SessionsSessionIdFilePutErrors, WriteFileAgentApiV1SessionsSessionIdFilePutResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Create a workspace session
 *
 * Allocate a workspace directory and open the MCP connection for a new agentic workspace session.
 */
export const createSessionAgentApiV1SessionsPost = <ThrowOnError extends boolean = false>(options?: Options<CreateSessionAgentApiV1SessionsPostData, ThrowOnError>): RequestResult<CreateSessionAgentApiV1SessionsPostResponses, CreateSessionAgentApiV1SessionsPostErrors, ThrowOnError> => (options?.client ?? client).post<CreateSessionAgentApiV1SessionsPostResponses, CreateSessionAgentApiV1SessionsPostErrors, ThrowOnError>({ url: '/agent/api/v1/sessions', ...options });

/**
 * End a workspace session
 *
 * Close the MCP connection, drop the history, and destroy the workspace directory and stored key.
 */
export const deleteSessionAgentApiV1SessionsSessionIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteSessionAgentApiV1SessionsSessionIdDeleteData, ThrowOnError>): RequestResult<DeleteSessionAgentApiV1SessionsSessionIdDeleteResponses, DeleteSessionAgentApiV1SessionsSessionIdDeleteErrors, ThrowOnError> => (options.client ?? client).delete<DeleteSessionAgentApiV1SessionsSessionIdDeleteResponses, DeleteSessionAgentApiV1SessionsSessionIdDeleteErrors, ThrowOnError>({ url: '/agent/api/v1/sessions/{session_id}', ...options });

/**
 * Get workspace session state
 *
 * Return session state, useful after a client reconnect.
 */
export const getSessionAgentApiV1SessionsSessionIdGet = <ThrowOnError extends boolean = false>(options: Options<GetSessionAgentApiV1SessionsSessionIdGetData, ThrowOnError>): RequestResult<GetSessionAgentApiV1SessionsSessionIdGetResponses, GetSessionAgentApiV1SessionsSessionIdGetErrors, ThrowOnError> => (options.client ?? client).get<GetSessionAgentApiV1SessionsSessionIdGetResponses, GetSessionAgentApiV1SessionsSessionIdGetErrors, ThrowOnError>({ url: '/agent/api/v1/sessions/{session_id}', ...options });

/**
 * Attach a BYOK credential to a session
 *
 * Store the user's Anthropic API key or auth token for this session only. Never send credentials as a chat message.
 */
export const setKeyAgentApiV1SessionsSessionIdKeyPost = <ThrowOnError extends boolean = false>(options: Options<SetKeyAgentApiV1SessionsSessionIdKeyPostData, ThrowOnError>): RequestResult<SetKeyAgentApiV1SessionsSessionIdKeyPostResponses, SetKeyAgentApiV1SessionsSessionIdKeyPostErrors, ThrowOnError> => (options.client ?? client).post<SetKeyAgentApiV1SessionsSessionIdKeyPostResponses, SetKeyAgentApiV1SessionsSessionIdKeyPostErrors, ThrowOnError>({
    url: '/agent/api/v1/sessions/{session_id}/key',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Send a chat message
 *
 * Append a user turn and start the tool loop. Returns immediately; progress arrives on the events stream.
 */
export const postMessageAgentApiV1SessionsSessionIdMessagesPost = <ThrowOnError extends boolean = false>(options: Options<PostMessageAgentApiV1SessionsSessionIdMessagesPostData, ThrowOnError>): RequestResult<PostMessageAgentApiV1SessionsSessionIdMessagesPostResponses, PostMessageAgentApiV1SessionsSessionIdMessagesPostErrors, ThrowOnError> => (options.client ?? client).post<PostMessageAgentApiV1SessionsSessionIdMessagesPostResponses, PostMessageAgentApiV1SessionsSessionIdMessagesPostErrors, ThrowOnError>({
    url: '/agent/api/v1/sessions/{session_id}/messages',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Interrupt the running turn
 *
 * Cancel the running turn, or a turn that was accepted but has not started yet. History rolls back to the pre-turn snapshot.
 */
export const interruptAgentApiV1SessionsSessionIdInterruptPost = <ThrowOnError extends boolean = false>(options: Options<InterruptAgentApiV1SessionsSessionIdInterruptPostData, ThrowOnError>): RequestResult<InterruptAgentApiV1SessionsSessionIdInterruptPostResponses, InterruptAgentApiV1SessionsSessionIdInterruptPostErrors, ThrowOnError> => (options.client ?? client).post<InterruptAgentApiV1SessionsSessionIdInterruptPostResponses, InterruptAgentApiV1SessionsSessionIdInterruptPostErrors, ThrowOnError>({ url: '/agent/api/v1/sessions/{session_id}/interrupt', ...options });

/**
 * Stream session events
 *
 * Server-sent events for one session: turn lifecycle, streamed text, tool calls/results, usage, and filesystem changes. See docs/API.md for the full event catalog.
 */
export const eventsAgentApiV1SessionsSessionIdEventsGet = <ThrowOnError extends boolean = false>(options: Options<EventsAgentApiV1SessionsSessionIdEventsGetData, ThrowOnError, EventsAgentApiV1SessionsSessionIdEventsGetResponse>): Promise<ServerSentEventsResult<EventsAgentApiV1SessionsSessionIdEventsGetResponses>> => (options.client ?? client).sse.get<EventsAgentApiV1SessionsSessionIdEventsGetResponses, EventsAgentApiV1SessionsSessionIdEventsGetErrors, ThrowOnError>({ url: '/agent/api/v1/sessions/{session_id}/events', ...options });

/**
 * List a workspace directory
 *
 * List one directory level (directories first, then files, both sorted). Omit path (or pass an empty string) for the workspace root.
 */
export const listFilesAgentApiV1SessionsSessionIdFilesGet = <ThrowOnError extends boolean = false>(options: Options<ListFilesAgentApiV1SessionsSessionIdFilesGetData, ThrowOnError>): RequestResult<ListFilesAgentApiV1SessionsSessionIdFilesGetResponses, ListFilesAgentApiV1SessionsSessionIdFilesGetErrors, ThrowOnError> => (options.client ?? client).get<ListFilesAgentApiV1SessionsSessionIdFilesGetResponses, ListFilesAgentApiV1SessionsSessionIdFilesGetErrors, ThrowOnError>({ url: '/agent/api/v1/sessions/{session_id}/files', ...options });

/**
 * Delete a workspace file or directory
 *
 * Delete one file or directory (recursively) from the tree pane.
 */
export const deleteFileAgentApiV1SessionsSessionIdFileDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteFileAgentApiV1SessionsSessionIdFileDeleteData, ThrowOnError>): RequestResult<DeleteFileAgentApiV1SessionsSessionIdFileDeleteResponses, DeleteFileAgentApiV1SessionsSessionIdFileDeleteErrors, ThrowOnError> => (options.client ?? client).delete<DeleteFileAgentApiV1SessionsSessionIdFileDeleteResponses, DeleteFileAgentApiV1SessionsSessionIdFileDeleteErrors, ThrowOnError>({ url: '/agent/api/v1/sessions/{session_id}/file', ...options });

/**
 * Read a workspace file
 *
 * Read one text file's content and ETag for the editor pane.
 */
export const readFileAgentApiV1SessionsSessionIdFileGet = <ThrowOnError extends boolean = false>(options: Options<ReadFileAgentApiV1SessionsSessionIdFileGetData, ThrowOnError>): RequestResult<ReadFileAgentApiV1SessionsSessionIdFileGetResponses, ReadFileAgentApiV1SessionsSessionIdFileGetErrors, ThrowOnError> => (options.client ?? client).get<ReadFileAgentApiV1SessionsSessionIdFileGetResponses, ReadFileAgentApiV1SessionsSessionIdFileGetErrors, ThrowOnError>({ url: '/agent/api/v1/sessions/{session_id}/file', ...options });

/**
 * Write a workspace file
 *
 * Create or overwrite one text file. Parent directories are created as needed. Send If-Match when saving a previously opened file.
 */
export const writeFileAgentApiV1SessionsSessionIdFilePut = <ThrowOnError extends boolean = false>(options: Options<WriteFileAgentApiV1SessionsSessionIdFilePutData, ThrowOnError>): RequestResult<WriteFileAgentApiV1SessionsSessionIdFilePutResponses, WriteFileAgentApiV1SessionsSessionIdFilePutErrors, ThrowOnError> => (options.client ?? client).put<WriteFileAgentApiV1SessionsSessionIdFilePutResponses, WriteFileAgentApiV1SessionsSessionIdFilePutErrors, ThrowOnError>({
    url: '/agent/api/v1/sessions/{session_id}/file',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
