// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * FileContentResponse
 *
 * Response returned when reading one workspace file.
 */
export type FileContentResponse = {
    /**
     * Path
     */
    path: string;
    /**
     * Content
     */
    content: string;
    /**
     * Etag
     */
    etag: string;
};

/**
 * FileEntryResponse
 *
 * One directory entry in a workspace file listing.
 */
export type FileEntryResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
    /**
     * Is Dir
     */
    is_dir: boolean;
};

/**
 * FileListResponse
 *
 * Response returned when listing one workspace directory level.
 */
export type FileListResponse = {
    /**
     * Path
     */
    path: string;
    /**
     * Entries
     */
    entries: Array<FileEntryResponse>;
};

/**
 * FileWriteRequest
 *
 * Full content of a file write.
 */
export type FileWriteRequest = {
    /**
     * Content
     */
    content: string;
};

/**
 * FileWriteResponse
 *
 * Response returned when writing one workspace file.
 */
export type FileWriteResponse = {
    /**
     * Path
     */
    path: string;
    /**
     * Etag
     */
    etag: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InterruptResponse
 *
 * Response returned when a running or queued turn is interrupted.
 */
export type InterruptResponse = {
    /**
     * Status
     */
    status: string;
};

/**
 * MessageCreateRequest
 *
 * A chat turn submitted to a session.
 */
export type MessageCreateRequest = {
    /**
     * Content
     */
    content: string;
};

/**
 * MessageCreateResponse
 *
 * Response returned when a chat turn is accepted.
 */
export type MessageCreateResponse = {
    /**
     * Turn Id
     */
    turn_id: string;
};

/**
 * SessionCreateResponse
 *
 * Response returned when a workspace session is created.
 */
export type SessionCreateResponse = {
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Session Token
     */
    session_token: string;
    /**
     * Model
     */
    model: string;
    /**
     * Tools
     */
    tools: Array<ToolDescriptor>;
};

/**
 * SessionKeyRequest
 *
 * BYOK credential upload for one session; provide exactly one field.
 */
export type SessionKeyRequest = {
    /**
     * Api Key
     */
    api_key?: string | null;
    /**
     * Auth Token
     */
    auth_token?: string | null;
};

/**
 * SessionStateResponse
 *
 * Point-in-time session state, useful after a client reconnect.
 */
export type SessionStateResponse = {
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Model
     */
    model: string;
    /**
     * Has Key
     */
    has_key: boolean;
    /**
     * Busy
     */
    busy: boolean;
    /**
     * Error
     */
    error: string | null;
    /**
     * Tools
     */
    tools: Array<ToolDescriptor>;
};

/**
 * ToolDescriptor
 *
 * One tool available to a session's agent loop.
 */
export type ToolDescriptor = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type CreateSessionAgentApiV1SessionsPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/agent/api/v1/sessions';
};

export type CreateSessionAgentApiV1SessionsPostErrors = {
    /**
     * Unknown session or invalid session token
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * MCP server unreachable or the session's MCP connection died
     */
    502: unknown;
};

export type CreateSessionAgentApiV1SessionsPostError = CreateSessionAgentApiV1SessionsPostErrors[keyof CreateSessionAgentApiV1SessionsPostErrors];

export type CreateSessionAgentApiV1SessionsPostResponses = {
    /**
     * Successful Response
     */
    201: SessionCreateResponse;
};

export type CreateSessionAgentApiV1SessionsPostResponse = CreateSessionAgentApiV1SessionsPostResponses[keyof CreateSessionAgentApiV1SessionsPostResponses];

export type DeleteSessionAgentApiV1SessionsSessionIdDeleteData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: {
        /**
         * Token
         */
        token?: string | null;
    };
    url: '/agent/api/v1/sessions/{session_id}';
};

export type DeleteSessionAgentApiV1SessionsSessionIdDeleteErrors = {
    /**
     * Unknown session or invalid session token
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSessionAgentApiV1SessionsSessionIdDeleteError = DeleteSessionAgentApiV1SessionsSessionIdDeleteErrors[keyof DeleteSessionAgentApiV1SessionsSessionIdDeleteErrors];

export type DeleteSessionAgentApiV1SessionsSessionIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteSessionAgentApiV1SessionsSessionIdDeleteResponse = DeleteSessionAgentApiV1SessionsSessionIdDeleteResponses[keyof DeleteSessionAgentApiV1SessionsSessionIdDeleteResponses];

export type GetSessionAgentApiV1SessionsSessionIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: {
        /**
         * Token
         */
        token?: string | null;
    };
    url: '/agent/api/v1/sessions/{session_id}';
};

export type GetSessionAgentApiV1SessionsSessionIdGetErrors = {
    /**
     * Unknown session or invalid session token
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSessionAgentApiV1SessionsSessionIdGetError = GetSessionAgentApiV1SessionsSessionIdGetErrors[keyof GetSessionAgentApiV1SessionsSessionIdGetErrors];

export type GetSessionAgentApiV1SessionsSessionIdGetResponses = {
    /**
     * Successful Response
     */
    200: SessionStateResponse;
};

export type GetSessionAgentApiV1SessionsSessionIdGetResponse = GetSessionAgentApiV1SessionsSessionIdGetResponses[keyof GetSessionAgentApiV1SessionsSessionIdGetResponses];

export type SetKeyAgentApiV1SessionsSessionIdKeyPostData = {
    body: SessionKeyRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: {
        /**
         * Token
         */
        token?: string | null;
    };
    url: '/agent/api/v1/sessions/{session_id}/key';
};

export type SetKeyAgentApiV1SessionsSessionIdKeyPostErrors = {
    /**
     * Invalid input: bad path, empty content, or missing key field
     */
    400: unknown;
    /**
     * Unknown session or invalid session token
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetKeyAgentApiV1SessionsSessionIdKeyPostError = SetKeyAgentApiV1SessionsSessionIdKeyPostErrors[keyof SetKeyAgentApiV1SessionsSessionIdKeyPostErrors];

export type SetKeyAgentApiV1SessionsSessionIdKeyPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type SetKeyAgentApiV1SessionsSessionIdKeyPostResponse = SetKeyAgentApiV1SessionsSessionIdKeyPostResponses[keyof SetKeyAgentApiV1SessionsSessionIdKeyPostResponses];

export type PostMessageAgentApiV1SessionsSessionIdMessagesPostData = {
    body: MessageCreateRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: {
        /**
         * Token
         */
        token?: string | null;
    };
    url: '/agent/api/v1/sessions/{session_id}/messages';
};

export type PostMessageAgentApiV1SessionsSessionIdMessagesPostErrors = {
    /**
     * Invalid input: bad path, empty content, or missing key field
     */
    400: unknown;
    /**
     * Unknown session or invalid session token
     */
    401: unknown;
    /**
     * Conflict: turn running, stale If-Match, filesystem error, or nothing to interrupt
     */
    409: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * No API key set for this session yet
     */
    428: unknown;
    /**
     * MCP server unreachable or the session's MCP connection died
     */
    502: unknown;
};

export type PostMessageAgentApiV1SessionsSessionIdMessagesPostError = PostMessageAgentApiV1SessionsSessionIdMessagesPostErrors[keyof PostMessageAgentApiV1SessionsSessionIdMessagesPostErrors];

export type PostMessageAgentApiV1SessionsSessionIdMessagesPostResponses = {
    /**
     * Successful Response
     */
    202: MessageCreateResponse;
};

export type PostMessageAgentApiV1SessionsSessionIdMessagesPostResponse = PostMessageAgentApiV1SessionsSessionIdMessagesPostResponses[keyof PostMessageAgentApiV1SessionsSessionIdMessagesPostResponses];

export type InterruptAgentApiV1SessionsSessionIdInterruptPostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: {
        /**
         * Token
         */
        token?: string | null;
    };
    url: '/agent/api/v1/sessions/{session_id}/interrupt';
};

export type InterruptAgentApiV1SessionsSessionIdInterruptPostErrors = {
    /**
     * Unknown session or invalid session token
     */
    401: unknown;
    /**
     * Conflict: turn running, stale If-Match, filesystem error, or nothing to interrupt
     */
    409: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InterruptAgentApiV1SessionsSessionIdInterruptPostError = InterruptAgentApiV1SessionsSessionIdInterruptPostErrors[keyof InterruptAgentApiV1SessionsSessionIdInterruptPostErrors];

export type InterruptAgentApiV1SessionsSessionIdInterruptPostResponses = {
    /**
     * Successful Response
     */
    202: InterruptResponse;
};

export type InterruptAgentApiV1SessionsSessionIdInterruptPostResponse = InterruptAgentApiV1SessionsSessionIdInterruptPostResponses[keyof InterruptAgentApiV1SessionsSessionIdInterruptPostResponses];

export type EventsAgentApiV1SessionsSessionIdEventsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: {
        /**
         * Token
         */
        token?: string | null;
    };
    url: '/agent/api/v1/sessions/{session_id}/events';
};

export type EventsAgentApiV1SessionsSessionIdEventsGetErrors = {
    /**
     * Unknown session or invalid session token
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EventsAgentApiV1SessionsSessionIdEventsGetError = EventsAgentApiV1SessionsSessionIdEventsGetErrors[keyof EventsAgentApiV1SessionsSessionIdEventsGetErrors];

export type EventsAgentApiV1SessionsSessionIdEventsGetResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type EventsAgentApiV1SessionsSessionIdEventsGetResponse = EventsAgentApiV1SessionsSessionIdEventsGetResponses[keyof EventsAgentApiV1SessionsSessionIdEventsGetResponses];

export type ListFilesAgentApiV1SessionsSessionIdFilesGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: {
        /**
         * Path
         */
        path?: string;
        /**
         * Token
         */
        token?: string | null;
    };
    url: '/agent/api/v1/sessions/{session_id}/files';
};

export type ListFilesAgentApiV1SessionsSessionIdFilesGetErrors = {
    /**
     * Invalid input: bad path, empty content, or missing key field
     */
    400: unknown;
    /**
     * Unknown session or invalid session token
     */
    401: unknown;
    /**
     * No such file or directory
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListFilesAgentApiV1SessionsSessionIdFilesGetError = ListFilesAgentApiV1SessionsSessionIdFilesGetErrors[keyof ListFilesAgentApiV1SessionsSessionIdFilesGetErrors];

export type ListFilesAgentApiV1SessionsSessionIdFilesGetResponses = {
    /**
     * Successful Response
     */
    200: FileListResponse;
};

export type ListFilesAgentApiV1SessionsSessionIdFilesGetResponse = ListFilesAgentApiV1SessionsSessionIdFilesGetResponses[keyof ListFilesAgentApiV1SessionsSessionIdFilesGetResponses];

export type DeleteFileAgentApiV1SessionsSessionIdFileDeleteData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query: {
        /**
         * Path
         */
        path: string;
        /**
         * Token
         */
        token?: string | null;
    };
    url: '/agent/api/v1/sessions/{session_id}/file';
};

export type DeleteFileAgentApiV1SessionsSessionIdFileDeleteErrors = {
    /**
     * Invalid input: bad path, empty content, or missing key field
     */
    400: unknown;
    /**
     * Unknown session or invalid session token
     */
    401: unknown;
    /**
     * No such file or directory
     */
    404: unknown;
    /**
     * Conflict: turn running, stale If-Match, filesystem error, or nothing to interrupt
     */
    409: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteFileAgentApiV1SessionsSessionIdFileDeleteError = DeleteFileAgentApiV1SessionsSessionIdFileDeleteErrors[keyof DeleteFileAgentApiV1SessionsSessionIdFileDeleteErrors];

export type DeleteFileAgentApiV1SessionsSessionIdFileDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteFileAgentApiV1SessionsSessionIdFileDeleteResponse = DeleteFileAgentApiV1SessionsSessionIdFileDeleteResponses[keyof DeleteFileAgentApiV1SessionsSessionIdFileDeleteResponses];

export type ReadFileAgentApiV1SessionsSessionIdFileGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query: {
        /**
         * Path
         */
        path: string;
        /**
         * Token
         */
        token?: string | null;
    };
    url: '/agent/api/v1/sessions/{session_id}/file';
};

export type ReadFileAgentApiV1SessionsSessionIdFileGetErrors = {
    /**
     * Invalid input: bad path, empty content, or missing key field
     */
    400: unknown;
    /**
     * Unknown session or invalid session token
     */
    401: unknown;
    /**
     * No such file or directory
     */
    404: unknown;
    /**
     * Conflict: turn running, stale If-Match, filesystem error, or nothing to interrupt
     */
    409: unknown;
    /**
     * Not a text file
     */
    415: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadFileAgentApiV1SessionsSessionIdFileGetError = ReadFileAgentApiV1SessionsSessionIdFileGetErrors[keyof ReadFileAgentApiV1SessionsSessionIdFileGetErrors];

export type ReadFileAgentApiV1SessionsSessionIdFileGetResponses = {
    /**
     * Successful Response
     */
    200: FileContentResponse;
};

export type ReadFileAgentApiV1SessionsSessionIdFileGetResponse = ReadFileAgentApiV1SessionsSessionIdFileGetResponses[keyof ReadFileAgentApiV1SessionsSessionIdFileGetResponses];

export type WriteFileAgentApiV1SessionsSessionIdFilePutData = {
    body: FileWriteRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
        /**
         * ETag from the last GET of this file; the write is rejected with 409 if the file changed since.
         */
        'If-Match'?: string;
    };
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query: {
        /**
         * Path
         */
        path: string;
        /**
         * Token
         */
        token?: string | null;
    };
    url: '/agent/api/v1/sessions/{session_id}/file';
};

export type WriteFileAgentApiV1SessionsSessionIdFilePutErrors = {
    /**
     * Invalid input: bad path, empty content, or missing key field
     */
    400: unknown;
    /**
     * Unknown session or invalid session token
     */
    401: unknown;
    /**
     * Conflict: turn running, stale If-Match, filesystem error, or nothing to interrupt
     */
    409: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WriteFileAgentApiV1SessionsSessionIdFilePutError = WriteFileAgentApiV1SessionsSessionIdFilePutErrors[keyof WriteFileAgentApiV1SessionsSessionIdFilePutErrors];

export type WriteFileAgentApiV1SessionsSessionIdFilePutResponses = {
    /**
     * Successful Response
     */
    200: FileWriteResponse;
};

export type WriteFileAgentApiV1SessionsSessionIdFilePutResponse = WriteFileAgentApiV1SessionsSessionIdFilePutResponses[keyof WriteFileAgentApiV1SessionsSessionIdFilePutResponses];
