"""Pydantic request and response schemas for the HTTP API."""

from src.api.schemas.adapters import (
    AdapterCatalogItemResponse,
    AdapterCatalogListResponse,
    AdapterDetailResponse,
    AdapterMetadataResponse,
)
from src.api.schemas.common import HealthResponse
from src.api.schemas.metadata import (
    ADAPTER_METADATA_GENERATE_EXAMPLE,
    DATASET_METADATA_GENERATE_EXAMPLE,
    METADATA_VALIDATE_DATASET_EXAMPLE,
    AdapterEmbeddedDatasetGenerateRequest,
    AdapterMetadataGenerateRequest,
    AdapterMetadataGenerateResponse,
    DatasetMetadataGenerateRequest,
    DatasetMetadataGenerateResponse,
    MetadataValidationCheckResponse,
    MetadataValidationRequest,
    MetadataValidationResponse,
)
from src.api.schemas.registrations import (
    REGISTRATION_CREATE_EXAMPLE,
    RegistrationCreateRequest,
    RegistrationCreateResponse,
    RegistrationDetailResponse,
    RegistrationEventListResponse,
    RegistrationEventResponse,
    RegistrationListItemResponse,
    RegistrationListResponse,
    RegistrationProcessResponse,
    RegistrationRevalidateResponse,
)
from src.api.schemas.registry import (
    RegistryEntryListResponse,
    RegistryEntryResponse,
    RegistryRefreshLatestResponse,
    RegistryRefreshResponse,
    RegistryRegistrationListResponse,
    RegistryRegistrationResponse,
)
from src.api.schemas.workspace import (
    FileContentResponse,
    FileEntryResponse,
    FileListResponse,
    FileWriteRequest,
    FileWriteResponse,
    InterruptResponse,
    MessageCreateRequest,
    MessageCreateResponse,
    SessionCreateResponse,
    SessionKeyRequest,
    SessionStateResponse,
    ToolDescriptor,
)

__all__ = [
    "ADAPTER_METADATA_GENERATE_EXAMPLE",
    "DATASET_METADATA_GENERATE_EXAMPLE",
    "METADATA_VALIDATE_DATASET_EXAMPLE",
    "REGISTRATION_CREATE_EXAMPLE",
    "AdapterCatalogItemResponse",
    "AdapterCatalogListResponse",
    "AdapterDetailResponse",
    "AdapterEmbeddedDatasetGenerateRequest",
    "AdapterMetadataGenerateRequest",
    "AdapterMetadataGenerateResponse",
    "AdapterMetadataResponse",
    "DatasetMetadataGenerateRequest",
    "DatasetMetadataGenerateResponse",
    "FileContentResponse",
    "FileEntryResponse",
    "FileListResponse",
    "FileWriteRequest",
    "FileWriteResponse",
    "HealthResponse",
    "InterruptResponse",
    "MessageCreateRequest",
    "MessageCreateResponse",
    "MetadataValidationCheckResponse",
    "MetadataValidationRequest",
    "MetadataValidationResponse",
    "RegistrationCreateRequest",
    "RegistrationCreateResponse",
    "RegistrationDetailResponse",
    "RegistrationEventListResponse",
    "RegistrationEventResponse",
    "RegistrationListItemResponse",
    "RegistrationListResponse",
    "RegistrationProcessResponse",
    "RegistrationRevalidateResponse",
    "RegistryEntryListResponse",
    "RegistryEntryResponse",
    "RegistryRefreshLatestResponse",
    "RegistryRefreshResponse",
    "RegistryRegistrationListResponse",
    "RegistryRegistrationResponse",
    "SessionCreateResponse",
    "SessionKeyRequest",
    "SessionStateResponse",
    "ToolDescriptor",
]
