"""Pydantic request and response schemas for the HTTP API."""

from src.api.schemas.adapters import (
    AdapterCatalogItemResponse,
    AdapterCatalogListResponse,
    AdapterDetailResponse,
    AdapterMetadataResponse,
    AdapterVersionResponse,
)
from src.api.schemas.common import HealthResponse
from src.api.schemas.metadata import (
    ADAPTER_METADATA_GENERATE_EXAMPLE,
    AdapterEmbeddedDatasetGenerateRequest,
    AdapterMetadataGenerateRequest,
    AdapterMetadataGenerateResponse,
    DATASET_METADATA_GENERATE_EXAMPLE,
    DatasetMetadataGenerateRequest,
    METADATA_VALIDATE_DATASET_EXAMPLE,
    DatasetMetadataGenerateResponse,
    MetadataValidationCheckResponse,
    MetadataValidationRequest,
    MetadataValidationResponse,
)
from src.api.schemas.registrations import (
    REGISTRATION_CREATE_EXAMPLE,
    RegistrationCreateRequest,
    RegistrationCreateResponse,
    RegistrationDetailResponse,
    RegistrationEventListResponse,
    RegistrationEventResponse,
    RegistrationListItemResponse,
    RegistrationListResponse,
    RegistrationProcessResponse,
    RegistrationRevalidateResponse,
)
from src.api.schemas.registry import (
    RegistryEntryListResponse,
    RegistryEntryResponse,
    RegistryRegistrationListResponse,
    RegistryRegistrationResponse,
    RegistryRefreshLatestResponse,
    RegistryRefreshResponse,
)

__all__ = [
    "AdapterCatalogItemResponse",
    "AdapterCatalogListResponse",
    "AdapterDetailResponse",
    "AdapterEmbeddedDatasetGenerateRequest",
    "ADAPTER_METADATA_GENERATE_EXAMPLE",
    "AdapterMetadataGenerateRequest",
    "AdapterMetadataGenerateResponse",
    "AdapterMetadataResponse",
    "AdapterVersionResponse",
    "DATASET_METADATA_GENERATE_EXAMPLE",
    "DatasetMetadataGenerateRequest",
    "DatasetMetadataGenerateResponse",
    "HealthResponse",
    "METADATA_VALIDATE_DATASET_EXAMPLE",
    "MetadataValidationCheckResponse",
    "MetadataValidationRequest",
    "MetadataValidationResponse",
    "REGISTRATION_CREATE_EXAMPLE",
    "RegistrationCreateRequest",
    "RegistrationCreateResponse",
    "RegistrationDetailResponse",
    "RegistrationEventListResponse",
    "RegistrationEventResponse",
    "RegistrationListItemResponse",
    "RegistrationListResponse",
    "RegistrationProcessResponse",
    "RegistrationRevalidateResponse",
    "RegistryEntryListResponse",
    "RegistryEntryResponse",
    "RegistryRegistrationListResponse",
    "RegistryRegistrationResponse",
    "RegistryRefreshLatestResponse",
    "RegistryRefreshResponse",
]
