from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest
from pytest_bdd import given, scenarios, then, when

from src.core.constants import METADATA_FILENAME
from src.core.generation.builder import build_adapter, build_creator, build_dataset
from src.core.validator import validate


scenarios("../features/us02_guided_metadata.feature")


@pytest.fixture
def work_dir(tmp_path: Path) -> Path:
    return tmp_path / "guided_flow"


@pytest.fixture
def guidance_context() -> dict[str, Any]:
    return {}


@given("a maintainer provides mandatory metadata inputs")
def maintainer_inputs(guidance_context: dict[str, Any]) -> None:
    guidance_context["inputs"] = {
        "name": "example-adapter",
        "description": "Example adapter metadata",
        "version": "0.1.0",
        "license": "MIT",
        "code_repository": "https://example.org/repo",
        "keywords": ["biology"],
        "creators": [build_creator("Ada Lovelace")],
        "datasets": [
            build_dataset(
                name="Example Dataset",
                description="Dataset description",
                version="1.0.0",
                license_url="CC-BY-4.0",
                url="https://example.org/dataset",
            )
        ],
    }


@when("the guided metadata flow completes")
def guided_flow_completes(
    guidance_context: dict[str, Any],
    work_dir: Path,
) -> None:
    work_dir.mkdir(parents=True, exist_ok=True)
    inputs = guidance_context["inputs"]
    doc = build_adapter(
        name=inputs["name"],
        description=inputs["description"],
        version=inputs["version"],
        license_url=inputs["license"],
        code_repository=inputs["code_repository"],
        creators=inputs["creators"],
        keywords=inputs["keywords"],
        datasets=inputs["datasets"],
    )
    output_path = work_dir / METADATA_FILENAME
    output_path.write_text(json.dumps(doc, indent=2), encoding="utf-8")
    guidance_context["output_path"] = output_path
    guidance_context["metadata"] = doc


@then("a croissant.jsonld file is generated")
def croissant_file_generated(guidance_context: dict[str, Any], work_dir: Path) -> None:
    output_path = guidance_context["output_path"]
    assert isinstance(output_path, Path)
    assert output_path.name == METADATA_FILENAME
    assert output_path.exists()
    assert output_path.parent == work_dir


@then("the generated file contains the provided mandatory fields")
def generated_file_contains_inputs(guidance_context: dict[str, Any]) -> None:
    metadata = guidance_context["metadata"]
    inputs = guidance_context["inputs"]
    assert metadata["name"] == inputs["name"]
    assert metadata["description"] == inputs["description"]
    assert metadata["version"] == inputs["version"]
    assert metadata["license"] == inputs["license"]
    assert metadata["codeRepository"] == inputs["code_repository"]


@given("a croissant.jsonld generated by the guided flow")
def generated_by_guided_flow(
    guidance_context: dict[str, Any],
    work_dir: Path,
) -> None:
    maintainer_inputs(guidance_context)
    guided_flow_completes(guidance_context, work_dir)


@when("the generated metadata is validated for mandatory fields")
def metadata_validated(guidance_context: dict[str, Any]) -> None:
    result = validate(guidance_context["metadata"])
    guidance_context["validation_result"] = result


@then("it passes the mandatory-field validation")
def passes_validation(guidance_context: dict[str, Any]) -> None:
    result = guidance_context["validation_result"]
    assert result.is_valid
    assert not result.errors


@given("mandatory inputs missing a required field")
def mandatory_inputs_missing_field(guidance_context: dict[str, Any]) -> None:
    guidance_context["inputs"] = {
        "name": "example-adapter",
        "description": "Example adapter metadata",
        "version": "0.1.0",
        "license": "MIT",
        "code_repository": "https://example.org/repo",
        "keywords": [],
        "creators": [build_creator("Ada Lovelace")],
        "datasets": [
            build_dataset(
                name="Example Dataset",
                description="Dataset description",
                version="1.0.0",
                license_url="CC-BY-4.0",
                url="https://example.org/dataset",
            )
        ],
    }


@then("mandatory-field validation fails")
def mandatory_validation_fails(guidance_context: dict[str, Any]) -> None:
    result = guidance_context["validation_result"]
    assert not result.is_valid
    assert result.errors
