Feature: Guided metadata generation

  Scenario: Generate croissant.jsonld from mandatory inputs
    Given a maintainer provides mandatory metadata inputs
    When the guided metadata flow completes
    Then a croissant.jsonld file is generated
    And the generated file contains the provided mandatory fields

  Scenario: Generated croissant.jsonld passes mandatory validation
    Given a croissant.jsonld generated by the guided flow
    When the generated metadata is validated for mandatory fields
    Then it passes the mandatory-field validation

  Scenario: Missing a mandatory field fails validation
    Given mandatory inputs missing a required field
    When the guided metadata flow completes
    And the generated metadata is validated for mandatory fields
    Then mandatory-field validation fails
