name: Snyk Security

on:
  push:
    branches: ["main" ]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read 
      security-events: write 
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SNYK_ORG: iulusoy
    steps:
      - uses: actions/checkout@v4
      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb

      - name: Snyk Open Source monitor
        run: snyk monitor --org="$SNYK_ORG" --all-projects

      - name: Snyk test and report
        run: |
          uv export --format requirements-txt --frozen --no-hashes -o requirements-snyk.txt
          snyk test --org="$SNYK_ORG" --file=requirements-snyk.txt --package-manager=pip
          snyk test --org="$SNYK_ORG" --file=frontend/package.json --package-manager=npm

        # Build the docker image for testing
      - name: Build a Docker image
        run: docker build -t biocypher-registry .
        # Runs Snyk Container (Container and SCA) analysis and uploads result to Snyk.
      - name: Snyk Container monitor
        run: snyk container monitor --org="$SNYK_ORG" biocypher-registry --file=Dockerfile

        # Push the Snyk Code results into GitHub Code Scanning tab
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
